// Requêtes par défaut pour peupler la base avec un catalogue varié
// quand le script d'import est lancé sans argument.
export const SEED_QUERIES = [
  // Genres / sujets
  "subject:fantasy",
  "subject:epic fantasy",
  "subject:science fiction",
  "subject:space opera",
  "subject:thriller",
  "subject:psychological thriller",
  "subject:mystery",
  "subject:cozy mystery",
  "subject:romance",
  "subject:contemporary romance",
  "subject:literary fiction",
  "subject:contemporary fiction",
  "subject:horror",
  "subject:historical fiction",
  "subject:young adult fiction",
  "subject:dystopian fiction",
  "subject:biography",
  "subject:memoir",
  "subject:true crime",
  "subject:poetry",
  "subject:graphic novels",
  "subject:manga",
  "subject:classics",
  "subject:short stories",
  "subject:french literature",
  "subject:self-help",
  "subject:popular science",
  "subject:philosophy",
  // Auteurs populaires, pour varier au-delà des résultats "subject:"
  'inauthor:"Agatha Christie"',
  'inauthor:"Stephen King"',
  'inauthor:"Jane Austen"',
  'inauthor:"Haruki Murakami"',
  'inauthor:"Toni Morrison"',
  'inauthor:"George R.R. Martin"',
  'inauthor:"Colleen Hoover"',
  'inauthor:"Brandon Sanderson"',
  'inauthor:"Margaret Atwood"',
  'inauthor:"Neil Gaiman"',
  'inauthor:"Gillian Flynn"',
  'inauthor:"Kazuo Ishiguro"',
  'inauthor:"Victor Hugo"',
  'inauthor:"Albert Camus"',
  'inauthor:"Amélie Nothomb"',
];

// Deuxième vague : sous-genres et auteurs supplémentaires pour élargir le catalogue
// au-delà de SEED_QUERIES. Passer ces requêtes explicitement à import-books.js
// (elles ne sont pas incluses dans le run par défaut, pour ne pas tout refaire à chaque fois).
export const MORE_QUERIES = [
  "subject:adventure",
  "subject:war fiction",
  "subject:crime fiction",
  "subject:noir fiction",
  "subject:urban fantasy",
  "subject:paranormal romance",
  "subject:steampunk",
  "subject:cyberpunk",
  "subject:post-apocalyptic fiction",
  "subject:children's fiction",
  "subject:fairy tales",
  "subject:cooking",
  "subject:business",
  "subject:psychology",
  "subject:health & fitness",
  "subject:travel",
  "subject:sports & recreation",
  "subject:religion",
  "subject:spirituality",
  "subject:political science",
  "subject:economics",
  "subject:computers",
  "subject:art",
  "subject:music",
  'inauthor:"J.R.R. Tolkien"',
  'inauthor:"J.K. Rowling"',
  'inauthor:"Isaac Asimov"',
  'inauthor:"Ursula K. Le Guin"',
  'inauthor:"Philip K. Dick"',
  'inauthor:"Ray Bradbury"',
  'inauthor:"Franz Kafka"',
  'inauthor:"Fyodor Dostoevsky"',
  'inauthor:"Leo Tolstoy"',
  'inauthor:"Gabriel García Márquez"',
  'inauthor:"Isabel Allende"',
  'inauthor:"Charles Dickens"',
  'inauthor:"Mark Twain"',
  'inauthor:"Ernest Hemingway"',
  'inauthor:"Virginia Woolf"',
  'inauthor:"George Orwell"',
  'inauthor:"Aldous Huxley"',
  'inauthor:"Paulo Coelho"',
  'inauthor:"Michel Houellebecq"',
  'inauthor:"Guillaume Musso"',
  'inauthor:"Marc Levy"',
  'inauthor:"Bernard Werber"',
  'inauthor:"Sally Rooney"',
  'inauthor:"John Green"',
  'inauthor:"Suzanne Collins"',
  'inauthor:"Rick Riordan"',
  'inauthor:"Cassandra Clare"',
  'inauthor:"Sarah J. Maas"',
  'inauthor:"Leigh Bardugo"',
];

// Troisième vague : grands classiques par tradition littéraire nationale/linguistique.
// Chaque requête "inauthor:" remonte le catalogue Google Books de l'auteur (souvent
// plusieurs dizaines d'éditions/œuvres différentes), donc c'est la manière la plus
// efficace de couvrir "les plus grands auteurs de chaque littérature".
export const CLASSICS_QUERIES = [
  // Russe
  'inauthor:"Anton Chekhov"',
  'inauthor:"Nikolai Gogol"',
  'inauthor:"Alexander Pushkin"',
  'inauthor:"Ivan Turgenev"',
  'inauthor:"Mikhail Bulgakov"',
  'inauthor:"Vladimir Nabokov"',
  // Française
  'inauthor:"Gustave Flaubert"',
  'inauthor:"Marcel Proust"',
  'inauthor:"Émile Zola"',
  'inauthor:"Honoré de Balzac"',
  'inauthor:"Voltaire"',
  'inauthor:"Stendhal"',
  'inauthor:"Alexandre Dumas"',
  'inauthor:"Marguerite Duras"',
  'inauthor:"Jean-Paul Sartre"',
  'inauthor:"Simone de Beauvoir"',
  // Anglaise / britannique
  'inauthor:"William Shakespeare"',
  'inauthor:"Charlotte Brontë"',
  'inauthor:"Emily Brontë"',
  'inauthor:"Thomas Hardy"',
  'inauthor:"Oscar Wilde"',
  'inauthor:"James Joyce"',
  // Américaine
  'inauthor:"F. Scott Fitzgerald"',
  'inauthor:"William Faulkner"',
  'inauthor:"John Steinbeck"',
  'inauthor:"Herman Melville"',
  'inauthor:"Edgar Allan Poe"',
  'inauthor:"Kurt Vonnegut"',
  'inauthor:"Harper Lee"',
  // Hispanophone / Amérique latine
  'inauthor:"Jorge Luis Borges"',
  'inauthor:"Mario Vargas Llosa"',
  'inauthor:"Pablo Neruda"',
  'inauthor:"Miguel de Cervantes"',
  'inauthor:"Julio Cortázar"',
  // Germanique
  'inauthor:"Johann Wolfgang von Goethe"',
  'inauthor:"Thomas Mann"',
  'inauthor:"Hermann Hesse"',
  // Italienne
  'inauthor:"Italo Calvino"',
  'inauthor:"Umberto Eco"',
  'inauthor:"Elena Ferrante"',
  'inauthor:"Dante Alighieri"',
  // Japonaise / est-asiatique
  'inauthor:"Yukio Mishima"',
  'inauthor:"Kenzaburo Oe"',
  'inauthor:"Natsume Soseki"',
  'inauthor:"Liu Cixin"',
  // Africaine / postcoloniale
  'inauthor:"Chinua Achebe"',
  'inauthor:"Chimamanda Ngozi Adichie"',
  'inauthor:"Wole Soyinka"',
  // Moyen-Orient / Asie du Sud
  'inauthor:"Naguib Mahfouz"',
  'inauthor:"Khaled Hosseini"',
  'inauthor:"Orhan Pamuk"',
  'inauthor:"Rabindranath Tagore"',
  'inauthor:"Salman Rushdie"',
  // Portugaise / brésilienne
  'inauthor:"José Saramago"',
  'inauthor:"Fernando Pessoa"',
  'inauthor:"Clarice Lispector"',
];

// Quatrième vague : titres précis très connus, recherchés par "intitle:...+inauthor:...".
// Contrairement à "subject:" (qui ne remonte qu'une vingtaine de résultats "populaires"
// selon Google, pas forcément les bons) ou "inauthor:" seul (qui peut noyer le titre
// recherché parmi des rééditions), cibler titre+auteur va chercher l'œuvre précise —
// utile pour les incontournables que les autres vagues manquent (ex: signalé par
// l'utilisateur : "Zero to One" absent malgré subject:business).
export const TITLE_QUERIES = [
  // Essais / développement personnel / business — mal couverts par subject:business générique
  "intitle:zero to one inauthor:thiel",
  "intitle:sapiens inauthor:harari",
  "intitle:thinking fast and slow inauthor:kahneman",
  "intitle:atomic habits inauthor:clear",
  "intitle:the lean startup inauthor:ries",
  "intitle:educated inauthor:westover",
  "intitle:man's search for meaning inauthor:frankl",
  "intitle:the power of habit inauthor:duhigg",
  "intitle:outliers inauthor:gladwell",
  "intitle:the 7 habits of highly effective people inauthor:covey",
  "intitle:deep work inauthor:newport",
  "intitle:the subtle art of not giving a f inauthor:manson",
  // Romans incontournables souvent noyés dans les résultats "subject:" ou "inauthor:"
  "intitle:the catcher in the rye inauthor:salinger",
  "intitle:the road inauthor:mccarthy",
  "intitle:the secret history inauthor:tartt",
  "intitle:normal people inauthor:rooney",
  "intitle:the kite runner inauthor:hosseini",
  "intitle:the handmaid's tale inauthor:atwood",
  "intitle:the night circus inauthor:morgenstern",
  "intitle:where the crawdads sing inauthor:owens",
  "intitle:the seven husbands of evelyn hugo inauthor:reid",
  "intitle:project hail mary inauthor:weir",
  "intitle:the martian inauthor:weir",
  "intitle:circe inauthor:miller",
  "intitle:the song of achilles inauthor:miller",
  "intitle:babel inauthor:kuang",
  "intitle:the invisible life of addie larue inauthor:schwab",
];

// Cinquième vague : best-sellers contemporains et auteurs grand public par catégorie,
// pour couvrir ce que les vagues précédentes (sujets génériques + classiques) manquent.
export const EXTRA_QUERIES = [
  // Thriller / polar grand public
  'inauthor:"Dan Brown"',
  'inauthor:"John Grisham"',
  'inauthor:"James Patterson"',
  'inauthor:"Lee Child"',
  'inauthor:"David Baldacci"',
  'inauthor:"Michael Connelly"',
  'inauthor:"Harlan Coben"',
  'inauthor:"Paula Hawkins"',
  'inauthor:"Richard Osman"',
  'inauthor:"Anthony Horowitz"',
  'inauthor:"Ian Rankin"',
  'inauthor:"Val McDermid"',
  'inauthor:"Freida McFadden"',
  // Polar nordique
  'inauthor:"Stieg Larsson"',
  'inauthor:"Jo Nesbø"',
  'inauthor:"Henning Mankell"',
  'inauthor:"Camilla Läckberg"',
  // Romance / feel-good grand public
  'inauthor:"Nicholas Sparks"',
  'inauthor:"Liane Moriarty"',
  'inauthor:"Danielle Steel"',
  'inauthor:"Nora Roberts"',
  'inauthor:"E.L. James"',
  'inauthor:"Emily Henry"',
  'inauthor:"Rebecca Yarros"',
  'inauthor:"Ken Follett"',
  // Polar / thriller français
  'inauthor:"Michel Bussi"',
  'inauthor:"Franck Thilliez"',
  'inauthor:"Fred Vargas"',
  'inauthor:"Virginie Grimaldi"',
  'inauthor:"Aurélie Valognes"',
  // Littérature coréenne / sud-asiatique
  'inauthor:"Han Kang"',
  'inauthor:"Min Jin Lee"',
  'inauthor:"Arundhati Roy"',
  'inauthor:"Vikram Seth"',
  'inauthor:"Amitav Ghosh"',
  // Jeunesse / classiques illustrés
  'inauthor:"Roald Dahl"',
  'inauthor:"C.S. Lewis"',
  'inauthor:"Astrid Lindgren"',
  'inauthor:"Antoine de Saint-Exupéry"',
  'inauthor:"Lewis Carroll"',
  'inauthor:"A.A. Milne"',
  // BD / manga incontournables
  'inauthor:"Eiichiro Oda"',
  'inauthor:"Akira Toriyama"',
  'inauthor:"Naoki Urasawa"',
  // Essais / vulgarisation scientifique / histoire
  'inauthor:"Bill Bryson"',
  'inauthor:"Carl Sagan"',
  'inauthor:"Jared Diamond"',
  'inauthor:"Mary Beard"',
  'inauthor:"Dan Ariely"',
  'inauthor:"Malcolm Gladwell"',
  // Développement personnel
  'inauthor:"Brené Brown"',
  'inauthor:"Ryan Holiday"',
  // Cuisine
  'inauthor:"Jamie Oliver"',
  'inauthor:"Yotam Ottolenghi"',
];

// Sixième vague : littérature française en profondeur, demandée explicitement par
// l'utilisateur — classiques (théâtre, fables, philosophie des Lumières), romantiques
// et poètes du XIXe, grands noms du XXe (dont les prix Nobel), best-sellers
// contemporains, et quelques titres emblématiques en complément (intitle:+inauthor:).
export const FRENCH_LITERATURE_QUERIES = [
  // Classiques (XVIe-XVIIIe : théâtre, fables, philosophie)
  'inauthor:"Molière"',
  'inauthor:"Jean Racine"',
  'inauthor:"Pierre Corneille"',
  'inauthor:"Jean de La Fontaine"',
  'inauthor:"Michel de Montaigne"',
  'inauthor:"François Rabelais"',
  'inauthor:"Denis Diderot"',
  'inauthor:"Jean-Jacques Rousseau"',
  'inauthor:"Blaise Pascal"',
  'inauthor:"Pierre Choderlos de Laclos"',
  // Romantisme / XIXe siècle
  'inauthor:"Charles Baudelaire"',
  'inauthor:"Arthur Rimbaud"',
  'inauthor:"Paul Verlaine"',
  'inauthor:"Guy de Maupassant"',
  'inauthor:"George Sand"',
  'inauthor:"Alphonse de Lamartine"',
  'inauthor:"Alphonse Daudet"',
  'inauthor:"Jules Verne"',
  'inauthor:"Edmond Rostand"',
  // XXe siècle (dont prix Nobel de littérature)
  'inauthor:"Marguerite Yourcenar"',
  'inauthor:"Colette"',
  'inauthor:"André Gide"',
  'inauthor:"André Malraux"',
  'inauthor:"Romain Gary"',
  'inauthor:"Boris Vian"',
  'inauthor:"Georges Perec"',
  'inauthor:"Patrick Modiano"',
  'inauthor:"J.M.G. Le Clézio"',
  'inauthor:"Annie Ernaux"',
  'inauthor:"Michel Tournier"',
  'inauthor:"Marcel Pagnol"',
  // Best-sellers contemporains
  'inauthor:"Joël Dicker"',
  'inauthor:"Pierre Lemaitre"',
  'inauthor:"David Foenkinos"',
  'inauthor:"Delphine de Vigan"',
  'inauthor:"Leïla Slimani"',
  'inauthor:"Anna Gavalda"',
  'inauthor:"Katherine Pancol"',
  'inauthor:"Éric-Emmanuel Schmitt"',
  'inauthor:"Frédéric Beigbeder"',
  'inauthor:"Tahar Ben Jelloun"',
  'inauthor:"Olivier Bourdeaut"',
  'inauthor:"Laurent Gounelle"',
  // Bande dessinée francophone
  'inauthor:"René Goscinny"',
  'inauthor:"Hergé"',
  // Titres emblématiques (au cas où noyés dans les résultats "inauthor:" ci-dessus)
  "intitle:les misérables inauthor:hugo",
  "intitle:le comte de monte-cristo inauthor:dumas",
  "intitle:notre-dame de paris inauthor:hugo",
  "intitle:madame bovary inauthor:flaubert",
  "intitle:du côté de chez swann inauthor:proust",
  "intitle:les liaisons dangereuses inauthor:laclos",
  "intitle:le petit prince inauthor:saint-exupéry",
];

// Septième vague : non-fiction ciblée (histoire, philosophie, biographie, entrepreneuriat,
// science) — ces thèmes restaient peu fournis car "subject:history"/"subject:philosophy"
// etc. (déjà dans MORE_QUERIES) ne remontent qu'une vingtaine de résultats génériques.
export const NONFICTION_QUERIES = [
  // Histoire
  'inauthor:"Yuval Noah Harari"',
  'inauthor:"Max Hastings"',
  'inauthor:"Antony Beevor"',
  'inauthor:"Niall Ferguson"',
  'inauthor:"Timothy Snyder"',
  'inauthor:"Ian Kershaw"',
  'inauthor:"Barbara Tuchman"',
  'inauthor:"William L. Shirer"',
  'inauthor:"Fernand Braudel"',
  'inauthor:"Georges Duby"',
  'inauthor:"Jacques Le Goff"',
  'inauthor:"Patrick Boucheron"',
  'inauthor:"Tom Holland"',
  'inauthor:"Simon Sebag Montefiore"',
  // Philosophie
  'inauthor:"Friedrich Nietzsche"',
  'inauthor:"Emmanuel Kant"',
  'inauthor:"Platon"',
  'inauthor:"Aristote"',
  'inauthor:"Michel Foucault"',
  'inauthor:"Gilles Deleuze"',
  'inauthor:"Jacques Derrida"',
  'inauthor:"Hannah Arendt"',
  'inauthor:"Bertrand Russell"',
  'inauthor:"Søren Kierkegaard"',
  'inauthor:"Georg Wilhelm Friedrich Hegel"',
  'inauthor:"Martin Heidegger"',
  'inauthor:"Baruch Spinoza"',
  'inauthor:"Épictète"',
  'inauthor:"Marc Aurèle"',
  'inauthor:"Luc Ferry"',
  'inauthor:"André Comte-Sponville"',
  'inauthor:"Michel Onfray"',
  // Biographie (auteurs spécialisés dans le genre)
  'inauthor:"Walter Isaacson"',
  'inauthor:"Ron Chernow"',
  'inauthor:"Robert Caro"',
  'inauthor:"David McCullough"',
  'inauthor:"Doris Kearns Goodwin"',
  'inauthor:"Ashlee Vance"',
  // Entrepreneuriat / business
  'inauthor:"Ben Horowitz"',
  'inauthor:"Guy Kawasaki"',
  'inauthor:"Reid Hoffman"',
  'inauthor:"Naval Ravikant"',
  'inauthor:"Tim Ferriss"',
  'inauthor:"Phil Knight"',
  'inauthor:"Sheryl Sandberg"',
  'inauthor:"Simon Sinek"',
  'inauthor:"Seth Godin"',
  'inauthor:"Jim Collins"',
  'inauthor:"Clayton Christensen"',
  // Science (vulgarisation)
  'inauthor:"Stephen Hawking"',
  'inauthor:"Neil deGrasse Tyson"',
  'inauthor:"Richard Dawkins"',
  'inauthor:"Brian Greene"',
  'inauthor:"Michio Kaku"',
  'inauthor:"Carlo Rovelli"',
  'inauthor:"Siddhartha Mukherjee"',
  'inauthor:"Jane Goodall"',
  'inauthor:"Frans de Waal"',
  'inauthor:"Hubert Reeves"',
  'inauthor:"Étienne Klein"',
  'inauthor:"Cédric Villani"',
];

// Huitième vague : non-fiction et genres en français spécifiquement — business,
// développement personnel, histoire, philosophie, sciences, SF étaient couverts
// presque exclusivement par des auteurs anglophones (ex: 0 résultat pour
// littérature=française + genre=business, signalé par l'utilisateur).
export const FRENCH_NONFICTION_QUERIES = [
  // Business / entrepreneuriat
  'inauthor:"Thomas Piketty"',
  'inauthor:"Jacques Attali"',
  'inauthor:"Nicolas Bouzou"',
  'inauthor:"Xavier Niel"',
  'inauthor:"Marc Simoncini"',
  'inauthor:"Isaac Getz"',
  'inauthor:"Olivier Sibony"',
  'inauthor:"Jean Tirole"',
  'inauthor:"Gaspard Koenig"',
  "subject:entrepreneuriat",
  "subject:gestion d'entreprise",
  // Développement personnel
  'inauthor:"Christophe André"',
  'inauthor:"Frédéric Lenoir"',
  'inauthor:"Thierry Janssen"',
  'inauthor:"Ilios Kotsou"',
  // Histoire (auteurs grand public contemporains)
  'inauthor:"Max Gallo"',
  'inauthor:"Franck Ferrand"',
  'inauthor:"Lorànt Deutsch"',
  'inauthor:"Jean-Christian Petitfils"',
  // Sciences (vulgarisation, en plus de Reeves/Klein/Villani déjà couverts)
  'inauthor:"Jean-Pierre Luminet"',
  'inauthor:"Aurélien Barrau"',
  'inauthor:"Idriss Aberkane"',
  // Science-fiction / fantasy française
  'inauthor:"Pierre Bordage"',
  'inauthor:"Alain Damasio"',
  'inauthor:"Jean-Marc Ligny"',
  'inauthor:"Catherine Dufour"',
  // Voyage / cuisine
  'inauthor:"Sylvain Tesson"',
  'inauthor:"Cyril Lignac"',
  'inauthor:"Philippe Etchebest"',
];
