// Requêtes par défaut pour peupler la base avec un catalogue varié
// quand le script d'import est lancé sans argument.
export const SEED_QUERIES = [
  // Genres / sujets
  "subject:fantasy",
  "subject:epic fantasy",
  "subject:science fiction",
  "subject:space opera",
  "subject:thriller",
  "subject:psychological thriller",
  "subject:mystery",
  "subject:cozy mystery",
  "subject:romance",
  "subject:contemporary romance",
  "subject:literary fiction",
  "subject:contemporary fiction",
  "subject:horror",
  "subject:historical fiction",
  "subject:young adult fiction",
  "subject:dystopian fiction",
  "subject:biography",
  "subject:memoir",
  "subject:true crime",
  "subject:poetry",
  "subject:graphic novels",
  "subject:manga",
  "subject:classics",
  "subject:short stories",
  "subject:french literature",
  "subject:self-help",
  "subject:popular science",
  "subject:philosophy",
  // Auteurs populaires, pour varier au-delà des résultats "subject:"
  'inauthor:"Agatha Christie"',
  'inauthor:"Stephen King"',
  'inauthor:"Jane Austen"',
  'inauthor:"Haruki Murakami"',
  'inauthor:"Toni Morrison"',
  'inauthor:"George R.R. Martin"',
  'inauthor:"Colleen Hoover"',
  'inauthor:"Brandon Sanderson"',
  'inauthor:"Margaret Atwood"',
  'inauthor:"Neil Gaiman"',
  'inauthor:"Gillian Flynn"',
  'inauthor:"Kazuo Ishiguro"',
  'inauthor:"Victor Hugo"',
  'inauthor:"Albert Camus"',
  'inauthor:"Amélie Nothomb"',
];

// Deuxième vague : sous-genres et auteurs supplémentaires pour élargir le catalogue
// au-delà de SEED_QUERIES. Passer ces requêtes explicitement à import-books.js
// (elles ne sont pas incluses dans le run par défaut, pour ne pas tout refaire à chaque fois).
export const MORE_QUERIES = [
  "subject:adventure",
  "subject:war fiction",
  "subject:crime fiction",
  "subject:noir fiction",
  "subject:urban fantasy",
  "subject:paranormal romance",
  "subject:steampunk",
  "subject:cyberpunk",
  "subject:post-apocalyptic fiction",
  "subject:children's fiction",
  "subject:fairy tales",
  "subject:cooking",
  "subject:business",
  "subject:psychology",
  "subject:health & fitness",
  "subject:travel",
  "subject:sports & recreation",
  "subject:religion",
  "subject:spirituality",
  "subject:political science",
  "subject:economics",
  "subject:computers",
  "subject:art",
  "subject:music",
  'inauthor:"J.R.R. Tolkien"',
  'inauthor:"J.K. Rowling"',
  'inauthor:"Isaac Asimov"',
  'inauthor:"Ursula K. Le Guin"',
  'inauthor:"Philip K. Dick"',
  'inauthor:"Ray Bradbury"',
  'inauthor:"Franz Kafka"',
  'inauthor:"Fyodor Dostoevsky"',
  'inauthor:"Leo Tolstoy"',
  'inauthor:"Gabriel García Márquez"',
  'inauthor:"Isabel Allende"',
  'inauthor:"Charles Dickens"',
  'inauthor:"Mark Twain"',
  'inauthor:"Ernest Hemingway"',
  'inauthor:"Virginia Woolf"',
  'inauthor:"George Orwell"',
  'inauthor:"Aldous Huxley"',
  'inauthor:"Paulo Coelho"',
  'inauthor:"Michel Houellebecq"',
  'inauthor:"Guillaume Musso"',
  'inauthor:"Marc Levy"',
  'inauthor:"Bernard Werber"',
  'inauthor:"Sally Rooney"',
  'inauthor:"John Green"',
  'inauthor:"Suzanne Collins"',
  'inauthor:"Rick Riordan"',
  'inauthor:"Cassandra Clare"',
  'inauthor:"Sarah J. Maas"',
  'inauthor:"Leigh Bardugo"',
];

// Troisième vague : grands classiques par tradition littéraire nationale/linguistique.
// Chaque requête "inauthor:" remonte le catalogue Google Books de l'auteur (souvent
// plusieurs dizaines d'éditions/œuvres différentes), donc c'est la manière la plus
// efficace de couvrir "les plus grands auteurs de chaque littérature".
export const CLASSICS_QUERIES = [
  // Russe
  'inauthor:"Anton Chekhov"',
  'inauthor:"Nikolai Gogol"',
  'inauthor:"Alexander Pushkin"',
  'inauthor:"Ivan Turgenev"',
  'inauthor:"Mikhail Bulgakov"',
  'inauthor:"Vladimir Nabokov"',
  // Française
  'inauthor:"Gustave Flaubert"',
  'inauthor:"Marcel Proust"',
  'inauthor:"Émile Zola"',
  'inauthor:"Honoré de Balzac"',
  'inauthor:"Voltaire"',
  'inauthor:"Stendhal"',
  'inauthor:"Alexandre Dumas"',
  'inauthor:"Marguerite Duras"',
  'inauthor:"Jean-Paul Sartre"',
  'inauthor:"Simone de Beauvoir"',
  // Anglaise / britannique
  'inauthor:"William Shakespeare"',
  'inauthor:"Charlotte Brontë"',
  'inauthor:"Emily Brontë"',
  'inauthor:"Thomas Hardy"',
  'inauthor:"Oscar Wilde"',
  'inauthor:"James Joyce"',
  // Américaine
  'inauthor:"F. Scott Fitzgerald"',
  'inauthor:"William Faulkner"',
  'inauthor:"John Steinbeck"',
  'inauthor:"Herman Melville"',
  'inauthor:"Edgar Allan Poe"',
  'inauthor:"Kurt Vonnegut"',
  'inauthor:"Harper Lee"',
  // Hispanophone / Amérique latine
  'inauthor:"Jorge Luis Borges"',
  'inauthor:"Mario Vargas Llosa"',
  'inauthor:"Pablo Neruda"',
  'inauthor:"Miguel de Cervantes"',
  'inauthor:"Julio Cortázar"',
  // Germanique
  'inauthor:"Johann Wolfgang von Goethe"',
  'inauthor:"Thomas Mann"',
  'inauthor:"Hermann Hesse"',
  // Italienne
  'inauthor:"Italo Calvino"',
  'inauthor:"Umberto Eco"',
  'inauthor:"Elena Ferrante"',
  'inauthor:"Dante Alighieri"',
  // Japonaise / est-asiatique
  'inauthor:"Yukio Mishima"',
  'inauthor:"Kenzaburo Oe"',
  'inauthor:"Natsume Soseki"',
  'inauthor:"Liu Cixin"',
  // Africaine / postcoloniale
  'inauthor:"Chinua Achebe"',
  'inauthor:"Chimamanda Ngozi Adichie"',
  'inauthor:"Wole Soyinka"',
  // Moyen-Orient / Asie du Sud
  'inauthor:"Naguib Mahfouz"',
  'inauthor:"Khaled Hosseini"',
  'inauthor:"Orhan Pamuk"',
  'inauthor:"Rabindranath Tagore"',
  'inauthor:"Salman Rushdie"',
  // Portugaise / brésilienne
  'inauthor:"José Saramago"',
  'inauthor:"Fernando Pessoa"',
  'inauthor:"Clarice Lispector"',
];

// Quatrième vague : titres précis très connus, recherchés par "intitle:...+inauthor:...".
// Contrairement à "subject:" (qui ne remonte qu'une vingtaine de résultats "populaires"
// selon Google, pas forcément les bons) ou "inauthor:" seul (qui peut noyer le titre
// recherché parmi des rééditions), cibler titre+auteur va chercher l'œuvre précise —
// utile pour les incontournables que les autres vagues manquent (ex: signalé par
// l'utilisateur : "Zero to One" absent malgré subject:business).
export const TITLE_QUERIES = [
  // Essais / développement personnel / business — mal couverts par subject:business générique
  "intitle:zero to one inauthor:thiel",
  "intitle:sapiens inauthor:harari",
  "intitle:thinking fast and slow inauthor:kahneman",
  "intitle:atomic habits inauthor:clear",
  "intitle:the lean startup inauthor:ries",
  "intitle:educated inauthor:westover",
  "intitle:man's search for meaning inauthor:frankl",
  "intitle:the power of habit inauthor:duhigg",
  "intitle:outliers inauthor:gladwell",
  "intitle:the 7 habits of highly effective people inauthor:covey",
  "intitle:deep work inauthor:newport",
  "intitle:the subtle art of not giving a f inauthor:manson",
  // Romans incontournables souvent noyés dans les résultats "subject:" ou "inauthor:"
  "intitle:the catcher in the rye inauthor:salinger",
  "intitle:the road inauthor:mccarthy",
  "intitle:the secret history inauthor:tartt",
  "intitle:normal people inauthor:rooney",
  "intitle:the kite runner inauthor:hosseini",
  "intitle:the handmaid's tale inauthor:atwood",
  "intitle:the night circus inauthor:morgenstern",
  "intitle:where the crawdads sing inauthor:owens",
  "intitle:the seven husbands of evelyn hugo inauthor:reid",
  "intitle:project hail mary inauthor:weir",
  "intitle:the martian inauthor:weir",
  "intitle:circe inauthor:miller",
  "intitle:the song of achilles inauthor:miller",
  "intitle:babel inauthor:kuang",
  "intitle:the invisible life of addie larue inauthor:schwab",
];
